### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by Kennric**
merge current development into master

### CODE REVIEW

**Comment by athai** [comment]
Before you merge develop into master, can we update the gitsubmodule first?

**Comment by athai** [comment]
Before you merge this into master, can we check that announcements are actually working properly (since @kelnera has been having difficulty with it)?

**Comment by Kennric** [comment]
@athai Right now it looks like the production site and staging site both are using the develop branch in the dougfir submodule - can you fix that?

Also, updating staging to the newest develop branch of dougfir does seem to fix announcements: 
http://cass.staging.osuosl.org/

**Comment by athai** [comment]
Awesome! I'll update which submodule each site is using once this gets merged.

**Pull request merged**
