### PR TITLE
Make title color configurable

### PR DESCRIPTION
**Pull request by subnomo**
In case we want a different colors for the title, it's now an option in the `pelicanconf.py`. The only color we have defined right now is blue, and it falls back to orange.

New colors can easily be added to the CSS by modifying this template:

```sass
.title-<color name here> {
    $title-color: <hex color here>;
    color: $title-color;

    &:hover, &:focus {
        color: $title-color;
    }

    // Topmost title
    @at-root {
        a.parent#{&}, .parent#{&}, a.parent:hover#{&} {
            color: <hex color here>;
        }
    }
}
```

### CODE REVIEW

**Comment by leian7** [comment]
This is great. Can you also make it so that when it is blue, the only hover/focus/active action that happens is an underline, like the EECS site? Right now when you turn it on to blue and hover over the title, it still turns dark brown.

**Comment by subnomo** [comment]
@leian7 Fixed.

**Comment by leian7** [comment]
+1

**Comment by alxngyn** [comment]
+1
Also, are we planning to use sass? 
(I've never used sass before) 
But I think sass has variables that we could use for color configs like this.

**Comment by subnomo** [comment]
@alxngyn Yes, @leian7 merged #40 a while back so we should all be using sass now instead of directly editing the css.

And yeah, I did use a local variable in the example. In the future if we decide to add more colors it would be a good idea to make a separate `colors.scss` file where we define them.

**Pull request merged**
