### PR TITLE
Update Header

### PR DESCRIPTION
**Pull request by athai**
Note, there are some issues that I couldn't figure out/resolve:
* The text for parent menus (i.e. About) will only be white if you're hovering over them
* There's a gap between the main menu and the submenu
* How should the search bar be handled?
* The font weight for the CASS heading is slightly off
* The font used for the article headings (in the slideshow) needs to be obtained from OSU

### CODE REVIEW

**Comment by kelnera** [comment]
@athai Thanks for your hard work! I can only answer a couple of these concerns. The CASS website will quickly be back on drupal (probably within the next week) so don't worry about issues with that site. Just make sure things look good for the OSL website. If you go to #78 there's a link to the branding pages and on the font page, they have alternative options for all three new fonts. I'll work on getting the official ones, but this should suffice for now.

**Comment by ramereth** [comment]
@athai looks like a great start! A few comments/answers

- I would try implementing search similar to how the eecs website does where it shows a search icon and then pops up a frame. If that's not easy to do then I'd recommend we just keep it as-is.
- The title heading for "OSU Open Source Lab" should be bold from what I can see on the EECS website
- This might be related to needing the fonts, but the fonts for the website itself seem to not be using the correct font for the body and headings.
- Looks like the new theme includes a background for the footer, we should probably try adding that
- When you look at the site in a mobile size, there seems to be some lingering CSS issues:
screenshot from 2017-05-31 10-03-41
.

**Comment by Kennric** [comment]
@ramereth you can see the results of my changes here: http://osuosl-pelican-175.staging.osuosl.org

**Comment by kelnera** [comment]
Great progress! I have a few more things I noticed:

- The titles of each page and big headers (like the headers for the blog feed) should also use the Impact font. It looks like most of the other font uses are more up in the air.

- This might be because we're using the substitute fonts, but I noticed the arrows between CASS and The Open Source Lab in the black bar are bigger and farther apart than on the rest of the OSU sites.

- Compare the OSL top hat orange with the OSU top hat orange; I don't think it's the same.

- When you shrink the window way down, the orange gets even darker...

- ...then when you make the window big again, the slideshow doesn't load properly.

Hopefully most of these are easy changes, although that last one might take more time so I won't ask that be fixed before we merge these changes; just something to keep an eye out for while you'll already be in the theme. Getting closer!

**Comment by Kennric** [comment]
@ramereth, @kelnera  I've updated a couple of things, the color and >> character, but the font EECS is using is a commercial font we don't want to add to the repo. I have not figured out the slideshow breakage on resize yet, and it might not be easily fixable - also it's a fairly edge case, I don't think users frequently resize while looking at the front page.

http://osuosl-pelican-175.staging.osuosl.org

**Comment by kelnera** [comment]
@Kennric Looks better and I think we're close. I knew the new fonts were specifically for OSU and they're not accessible to the public (or easy to download) so it's nice they've offered the alternative fonts. I think the only thing I would like to change before merging is applying the Impact font (alternative to Stratum 2) to the page headers and the blog feed. But I also know we're on a time crunch so if we need to push as is we can just make an issue.

**Comment by ramereth** [comment]
@Kennric I think this is basically ready for desktops, but on mobile or responsive it seems to have a few issues specifically in the header section. There also seems to be quite a bit of white space from the image banner to the text below:

screenshot from 2017-07-27 08-48-00

In comparison, the EECS website looks like this:

screenshot from 2017-07-27 08-49-41

**Comment by ramereth** [comment]
@JerryPeng0112 please feel free to merge this and then create a new PR which merges develop into master.

**Pull request merged**
