### PR TITLE
Leian/sync scss

### PR DESCRIPTION
**Pull request by leian7**
Addresses #37 . The compiled form of main.scss now matches main.css; no variables have been made yet. Any suggestions as to what to variable-ize besides title color?

To test this PR:
1. In static/css/, ``sass main.scss temp.css`` to generate the css from main.scss.
2. ``diff temp.css main.css`` to confirm that they now match

@subnomo @athai @Kennric @alxngyn

### CODE REVIEW

**Comment by subnomo** [comment]
Looks good, but maybe you should add the main.css.map since the main.css points to it.

**Comment by leian7** [comment]
@subnomo Thanks. It looks like source maps are generated automatically upon compile, and someone already put *.map in the .gitignore. Should we start tracking maps anyway?

**Comment by subnomo** [comment]
@leian7 Good question. I actually don't think we should be tracking generated files at all, we *should* remove main.css from the repo and add it to the .gitignore.

But then we'd have to make pelican generate the css, and I think that's out of scope for this PR. For now, I'll just give my +1.

**Comment by athai** [comment]
+1

**Comment by athai** [comment]
Hold off on merging. Header has turned back to orange.

**Comment by subnomo** [comment]
Good work, looks good :+1:

**Pull request merged**
