### PR TITLE
Add customfilters.py to theme

### PR DESCRIPTION
**Pull request by matthewrsj**
Add custom jinja filters to theme so they are not duplicated in pelican sites.

### CODE REVIEW

**Comment by matthewrsj** [comment]
@ramereth @Kennric

**Comment by Kennric** [comment]
+1

**Comment by ramereth** [comment]
@Kennric you ok having this in the root of the repo?

**Comment by Kennric** [comment]
@ramereth Good point, I was looking at code, not location. I think a scripts directory is probably a good idea, though I don't think the root will hurt anything - especially if we move pretty quickly on to the new osu theme and don't accumulate a lot of other code here.

**Comment by ramereth** [comment]
:+1:

**Comment by matthewrsj** [comment]
I created a `filters` directory since `[Ss]cripts` is in the `.gitignore`

**Comment by Kennric** [comment]
+1

**Pull request merged**
